AI_AGENT Embedded C Project: led_blink.c File Reference
led_blink.c File Reference
#include <stdint.h>
#include "app/app_main.h"
Macros
#define LED_PORT PORTB
#define LED_DDR DDRB
#define LED_PIN 0
Functions
void delay_ms (uint16_t ms)
Delays execution for a specified number of milliseconds.
int main (void)
Main entry point. Calls application main.
Macro Definition Documentation
LED_DDR
#define LED_DDR DDRB
Definition at line 6 of file led_blink.c.
Referenced by main().
LED_PIN
#define LED_PIN 0
Definition at line 7 of file led_blink.c.
Referenced by main().
LED_PORT
#define LED_PORT PORTB
Definition at line 5 of file led_blink.c.
Referenced by main().
Function Documentation
delay_ms()
void delay_ms (uint16_t ms)
Delays execution for a specified number of milliseconds.
Parameters
ms Number of milliseconds to delay.
Definition at line 9 of file led_blink.c.
{
    // Simple delay loop (not accurate, for demonstration only)
    volatile uint32_t count;
    while (ms--) {
        count = 1000;
        while (count--);
    }
}
Referenced by main().
main()
int main (void)
Main entry point. Calls application main.
Returns
int 0 on success.
Definition at line 22 of file led_blink.c.
{
    // Set LED pin as output
    LED_DDR |= (1 << LED_PIN);
    while (1) {
        // Turn LED on
        LED_PORT |= (1 << LED_PIN);
        delay_ms(500);
        // Turn LED off
        LED_PORT &= ~(1 << LED_PIN);
        delay_ms(500);
    }
    return app_main();
}
References app_main(), delay_ms(), LED_DDR, LED_PIN, and LED_PORT.