AI_AGENT Embedded C Project: inc/hal/led_hal.h File Reference
led_hal.h File Reference
#include <stdint.h>
Functions
void led_init (void)
Initializes the LED hardware (sets the pin as output).
void led_on (void)
Turns the LED on.
void led_off (void)
Turns the LED off.
Function Documentation
led_init()
void led_init (void)
Initializes the LED hardware (sets the pin as output).
Definition at line 12 of file led_hal.c.
{
    LED_DDR |= (1 << LED_PIN);
}
References LED_DDR, and LED_PIN.
Referenced by app_main().
led_off()
void led_off (void)
Turns the LED off.
Definition at line 22 of file led_hal.c.
{
    LED_PORT &= ~(1 << LED_PIN);
}
References LED_PIN, and LED_PORT.
Referenced by app_main().
led_on()
void led_on (void)
Turns the LED on.
Definition at line 17 of file led_hal.c.
{
    LED_PORT |= (1 << LED_PIN);
}
References LED_PIN, and LED_PORT.
Referenced by app_main().